apiVersion: v1
kind: Pod #K8s object type
metadata:
  name: webapp #Pod name
  labels:
    app: webapp
    release: "0"
spec:
  containers: #A list because multiple container can run in one pod (not recommended)
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
