apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-storage-class #must match corresponding persistentVolume
  accessModes: # This field is required
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi #This specifies how much storage is required. K8s will try to allocate it.

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: local-storage-class #must match corresponding persistentVolumeClaim
  capacity: # This field is required
    storage: 20Gi # Must be equal to or greater than the storage defined in the persistenceVolumeClaim
  accessModes: # This field is required
    - ReadWriteOnce
  hostPath: # specifies how mounting should be implemented ()
    path: /mnt/mypvc/mydb # path in Linux version machine
    type: DirectoryOrCreate # If nothing exists at the given path, an empty directory will be create